### ISSUE TITLE
Saving an empty diagram will crash

### ISSUE THREAD

**Issue by mario-nolte** [xmf-xmodeler/MosaicFX#293]
Saving an empty diagram will crash:
java.lang.NullPointerException
        at tool.clients.serializer.FmmlxSerializer.saveAsXml(FmmlxSerializer.java:56)
        at tool.clients.fmmlxdiagrams.FmmlxDiagramCommunicator$3.call(FmmlxDiagramCommunicator.java:1787)
        at tool.clients.fmmlxdiagrams.FmmlxDiagramCommunicator$3.call(FmmlxDiagramCommunicator.java:1)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Expected behaviour:
- allow to save also empty diagrams
- message that at least one element has to be modeled

**Comment by dtoepel** [comment]
not reproducable...
FmmlxSerializer.java:56 suggests somethinh went wrong with diagram ids

tried with more than one Project open, and with a failed one (#292), but still working
